import { getMyAddresses, saveMyAddress, deleteMyAddress } from './firebase-data.js';

const container=()=>document.getElementById('addressContainer');
let editing=null;
let authReady=false;
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
function formHtml(a={}){return `<div class="address-card"><h2>${a.firestoreId?'Edit Address':'Add New Address'}</h2><form id="addressForm" class="address-form"><label>Address Label<input name="label" value="${esc(a.label||'Home')}" placeholder="Home, Work, School..." required></label><label>Full Name<input name="fullName" value="${esc(a.fullName||window.lexFirebase?.profile?.name||window.lexFirebase?.user?.displayName||'')}" autocomplete="name" required></label><label>Phone Number<input name="phone" value="${esc(a.phone||window.lexFirebase?.profile?.phone||'')}" autocomplete="tel" inputmode="tel" required></label><label>State<input name="state" value="${esc(a.state||'')}" placeholder="e.g. Delta State" required></label><label>City / Town<input name="city" value="${esc(a.city||'')}" placeholder="e.g. Asaba" required></label><label>Street Address<textarea name="address" placeholder="House number, street name, area..." required>${esc(a.address||'')}</textarea></label><label>Landmark <span class="muted">(Optional)</span><input name="landmark" value="${esc(a.landmark||'')}" placeholder="Nearby landmark, junction..."></label><label class="address-check"><input type="checkbox" name="isDefault" ${a.isDefault||!a.firestoreId?'checked':''}> Make this my default address</label><div class="address-actions"><button class="btn primary" type="submit">${a.firestoreId?'Save Changes':'Save Address'}</button>${a.firestoreId?'<button class="btn secondary dark-outline" type="button" id="cancelEdit">Cancel</button>':''}</div></form></div>`}
function listHtml(list){if(!list.length)return '<div class="address-card empty-address"><div style="font-size:42px">📍</div><h2>No saved addresses</h2><p>Add your first delivery address to make checkout faster.</p></div>';return `<div class="address-card"><h2>Saved Addresses</h2>${list.map(a=>`<div class="saved-address ${a.isDefault?'default':''}"><div class="saved-top"><strong>📍 ${esc(a.label)}</strong>${a.isDefault?'<span class="default-badge">Default</span>':''}</div><p><b>${esc(a.fullName)}</b> · ${esc(a.phone)}</p><p>${esc(a.address)}, ${esc(a.city)}, ${esc(a.state)}</p>${a.landmark?`<p>Landmark: ${esc(a.landmark)}</p>`:''}<div class="saved-actions"><button class="btn secondary dark-outline" data-edit="${a.firestoreId}">Edit</button><button class="btn secondary dark-outline" data-delete="${a.firestoreId}">Delete</button></div></div>`).join('')}</div>`}
async function render(){const b=container();if(!b)return;
if(!authReady && !window.lexFirebase?.user){b.innerHTML='<div class="address-card empty-address"><div style="font-size:42px">📍</div><h2>Loading your account…</h2><p>Please wait while we load your saved addresses.</p></div>';return}
if(!window.lexFirebase?.user){b.innerHTML='<div class="address-card empty-address"><h2>Sign in required</h2><p>Please sign in to manage your saved addresses.</p><a class="btn primary" href="auth.html?next=addresses.html">Sign In</a></div>';return}try{const list=await getMyAddresses();b.innerHTML=`<div class="address-grid">${formHtml(editing||{})}${listHtml(list)}</div>`;bind(list)}catch(e){b.innerHTML=`<div class="address-card"><h2>Could not load addresses</h2><p>${esc(e.message||'Please try again.')}</p></div>`}}
function bind(list){const form=document.getElementById('addressForm');form?.addEventListener('submit',async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(form).entries());data.isDefault=form.elements.isDefault.checked;try{await saveMyAddress({...data,firestoreId:editing?.firestoreId});editing=null;await render()}catch(err){alert(err.message||'Could not save address')}});document.getElementById('cancelEdit')?.addEventListener('click',()=>{editing=null;render()});document.querySelectorAll('[data-edit]').forEach(btn=>btn.addEventListener('click',()=>{editing=list.find(x=>x.firestoreId===btn.dataset.edit)||null;render()}));document.querySelectorAll('[data-delete]').forEach(btn=>btn.addEventListener('click',async()=>{if(!confirm('Delete this saved address?'))return;try{await deleteMyAddress(btn.dataset.delete);await render()}catch(e){alert(e.message||'Could not delete address')}}))}
window.addEventListener('lex-auth-changed',()=>{authReady=true;editing=null;render()});document.addEventListener('DOMContentLoaded',()=>{setTimeout(render,350);});
