const CART_KEY='lexMarketCart', WISH_KEY='lexMarketWishlist', ORDER_KEY='lexMarketOrders', USER_KEY='lexMarketUser';
const money=n=>'₦'+Number(n).toLocaleString('en-NG');
const get=(key,fallback=[])=>{try{return JSON.parse(localStorage.getItem(key))??fallback}catch(e){return fallback}};
const cart=()=>get(CART_KEY,[]); const wish=()=>get(WISH_KEY,[]); const orders=()=>get(ORDER_KEY,[]);
const saveCart=c=>{localStorage.setItem(CART_KEY,JSON.stringify(c));updateCounts()};
const enrich={1:{description:'Titanium design, powerful performance and a pro camera system.',stock:18},2:{description:'Premium Android flagship with an advanced camera and bright display.',stock:24},3:{description:'Wireless earbuds with clear sound, comfortable fit and long battery life.',stock:42},4:{description:'Reliable everyday laptop for school, work and entertainment.',stock:12},5:{description:'Next-generation gaming console with immersive graphics and fast loading.',stock:9},6:{description:'Premium wireless earbuds with active noise cancellation.',stock:21},7:{description:'Affordable everyday laptop for students, work and home use.',stock:16},8:{description:'Responsive wireless controller for console and PC gaming.',stock:30}};
products.forEach(p=>Object.assign(p,enrich[p.id]||{}));
function updateCounts(){const c=cart().reduce((s,x)=>s+Number(x.quantity||0),0);document.querySelectorAll('.cart-link').forEach(link=>{let b=link.querySelector('.cart-badge');if(!b){b=document.createElement('span');b.className='cart-badge';link.appendChild(b)}b.textContent=c;b.classList.toggle('empty',c===0)})}
function inWish(id){return wish().some(x=>x.id===Number(id))}
function toggleWishlist(id){id=Number(id);const p=products.find(x=>x.id===id);if(!p)return;let w=wish();const i=w.findIndex(x=>x.id===id);i>=0?w.splice(i,1):w.push({...p});localStorage.setItem(WISH_KEY,JSON.stringify(w));renderAll();showToast(i>=0?'Removed from wishlist':'Added to wishlist')}
function addToCart(id,qty=1){id=Number(id);qty=Math.max(1,Number(qty)||1);const p=products.find(x=>x.id===id);if(!p)return;let c=cart(),item=c.find(x=>x.id===id);if(item)item.quantity+=qty;else c.push({id:p.id,name:p.name,price:p.price,image:p.image,quantity:qty});saveCart(c);showToast(p.name+' added to cart')}
function removeFromCart(id){saveCart(cart().filter(x=>x.id!==Number(id)));renderCart();showToast('Item removed')}
function changeQty(id,delta){id=Number(id);let c=cart(),i=c.findIndex(x=>x.id===id);if(i<0)return;c[i].quantity+=delta;if(c[i].quantity<=0)c.splice(i,1);saveCart(c);renderCart()}
function imageTag(p,cls='product-image'){return `<div class="product-photo"><img class="${cls}" src="${p.image}" alt="${p.name}" loading="lazy" onerror="this.style.display='none';this.parentElement.classList.add('image-missing')"></div>`}
function productCard(p,variant=''){return `<article class="card ${variant}"><div class="pic" onclick="openProduct(${p.id})"><span class="discount">${p.discount}% OFF</span><button class="heart ${inWish(p.id)?'saved':''}" onclick="event.stopPropagation();toggleWishlist(${p.id})">${inWish(p.id)?'♥':'♡'}</button>${imageTag(p)}</div><div class="card-body"><small>${p.category}</small><h3 onclick="openProduct(${p.id})">${p.name}</h3><div class="rating">★ ${p.rating} <small>(${p.reviews})</small></div><div class="price"><strong>${money(p.price)}</strong><del>${money(p.oldPrice)}</del></div><button class="add" onclick="addToCart(${p.id})">Add to Cart</button></div></article>`}
function openProduct(id){location.href='product.html?id='+id}
let currentCategory='All',currentSearch='';
function renderProducts(){const b=document.getElementById('productsContainer');if(!b)return;let list=products.filter(p=>(currentCategory==='All'||p.category===currentCategory)&&p.name.toLowerCase().includes(currentSearch.toLowerCase()));b.innerHTML=list.map(productCard).join('');document.getElementById('noProducts')?.classList.toggle('hidden',list.length>0);const rc=document.getElementById('resultCount');if(rc)rc.textContent=list.length+' products'}
function renderHome(){const b=document.getElementById('homeProducts');if(b)b.innerHTML=products.slice(0,4).map(p=>productCard(p,'deal-card')).join('');const f=document.getElementById('featuredProducts');if(f)f.innerHTML=products.slice(4,8).map(p=>productCard(p,'featured-card')).join('')}
function renderDeals(){const b=document.getElementById('dealsContainer');if(b)b.innerHTML=products.slice().sort((a,b)=>b.discount-a.discount).map(productCard).join('')}
function renderWishlist(){const b=document.getElementById('wishlistContainer');if(!b)return;const w=wish();b.innerHTML=w.length?`<div class="wish-list">${w.map(item=>{const p=products.find(x=>x.id===Number(item.id))||item;return `<div class="wish-item"><div class="wish-img">${imageTag(p,'small-product-image')}</div><div><small>${p.category}</small><h3 onclick="openProduct(${p.id})">${p.name}</h3><strong>${money(p.price)}</strong></div><div class="wish-actions"><button class="add" onclick="addToCart(${p.id})">Add to Cart</button><button class="remove" onclick="toggleWishlist(${p.id})">Remove</button></div></div>`}).join('')}</div>`:`<div class="empty"><div>♡</div><h2>Your Wishlist is Empty</h2><p>Save products you love and find them here later.</p><a class="btn primary" href="products.html">Browse Products</a></div>`}
function renderCart(){const b=document.getElementById('cartContainer');if(!b)return;const c=cart();if(!c.length){b.innerHTML=`<div class="empty"><div>🛒</div><h2>Your Cart is Empty</h2><p>Add some products to your cart to get started.</p><a class="btn primary" href="products.html">Start Shopping</a></div>`;return}let sub=0;b.innerHTML=`<div class="cart-layout"><div class="cart-list">${c.map(x=>{const p=products.find(y=>y.id===Number(x.id))||x,total=p.price*x.quantity;sub+=total;return `<div class="cart-item"><div class="cart-img">${imageTag(p,'small-product-image')}</div><div class="cart-info"><h3>${p.name}</h3><strong>${money(p.price)}</strong></div><div class="cart-side"><div class="qty"><button onclick="changeQty(${p.id},-1)">−</button><b>${x.quantity}</b><button onclick="changeQty(${p.id},1)">+</button></div><strong>${money(total)}</strong><button class="remove" onclick="removeFromCart(${p.id})">Remove</button></div></div>`}).join('')}</div><aside class="summary"><h2>Order Summary</h2><div><span>Subtotal</span><strong>${money(sub)}</strong></div><div><span>Delivery</span><strong>₦2,500</strong></div><div class="total"><span>Total</span><strong>${money(sub+2500)}</strong></div><a class="btn primary" href="checkout.html">Proceed to Checkout</a><a class="continue-shopping" href="products.html">Continue Shopping</a></aside></div>`}
function renderCheckout(){const b=document.getElementById('checkoutContainer');if(!b)return;const c=cart();if(!c.length){b.innerHTML=`<div class="empty"><div>🛒</div><h2>Your Cart is Empty</h2><a class="btn primary" href="products.html">Browse Products</a></div>`;return}let sub=c.reduce((s,x)=>s+x.price*x.quantity,0),fee=2500;b.querySelector('#checkoutSummary').innerHTML=`<div><span>Subtotal</span><strong>${money(sub)}</strong></div><div><span>Delivery</span><strong>${money(fee)}</strong></div><div class="total"><span>Total</span><strong>${money(sub+fee)}</strong></div>`}
function renderProduct(){const b=document.getElementById('productDetails');if(!b)return;const id=Number(new URLSearchParams(location.search).get('id')),p=products.find(x=>x.id===id);if(!p){b.innerHTML='<div class="empty"><h2>Product Not Found</h2><a class="btn primary" href="products.html">Browse Products</a></div>';return}b.innerHTML=`<a class="back" href="products.html">← Back to Products</a><div class="details"><div class="details-pic">${imageTag(p,'detail-product-image')}<span class="discount">${p.discount}% OFF</span></div><div><small>${p.category}</small><h1>${p.name}</h1><div class="rating">★ ${p.rating} (${p.reviews} reviews)</div><div class="details-price"><strong>${money(p.price)}</strong><del>${money(p.oldPrice)}</del></div><p>${p.description}</p><p class="stock">✓ ${p.stock} available</p><div class="quantity-control"><button onclick="adjustDetailQty(-1)">−</button><input id="detailQty" value="1" readonly><button onclick="adjustDetailQty(1)">+</button></div><div class="product-actions"><button class="add big" onclick="addToCart(${p.id},Number(document.getElementById('detailQty').value))">🛒 Add to Cart</button><button class="wish-detail" onclick="toggleWishlist(${p.id})">${inWish(p.id)?'♥ Saved':'♡ Wishlist'}</button></div></div></div><div class="reviews-box"><h2>Customer Reviews</h2><div class="review-summary"><strong>★ ${p.rating}</strong><span>Based on ${p.reviews} reviews</span></div><div class="review"><b>Verified buyer</b><span>Great product and exactly as described.</span></div><div class="review"><b>Verified buyer</b><span>Good value and fast delivery.</span></div></div>`}
function adjustDetailQty(d){const i=document.getElementById('detailQty');if(!i)return;i.value=Math.max(1,Math.min(10,Number(i.value)+d))}
function renderAccount(){const b=document.getElementById('accountContainer');if(!b)return;const o=orders();const user=get(USER_KEY,null);b.innerHTML=`<div class="account-grid"><div class="account-card"><div class="avatar">👤</div><h2>${user?.name||'Welcome to LEX Market'}</h2><p>${user?.email||'Guest account'}</p><a class="btn primary" href="products.html">Continue Shopping</a></div><div class="account-card"><h2>My Orders</h2>${o.length?o.slice().reverse().map(x=>`<div class="order-row"><b>${x.id}</b><span>${x.status}</span><a href="tracking.html?id=${encodeURIComponent(x.id)}">Track</a></div>`).join(''):'<p>No orders yet.</p>'}</div></div>`}
function renderTracking(){const b=document.getElementById('trackingContainer');if(!b)return;const id=new URLSearchParams(location.search).get('id'),list=orders(),o=list.find(x=>x.id===id)||list[list.length-1];if(!o){b.innerHTML='<div class="empty"><div>📦</div><h2>No Order Found</h2><p>Place an order first to track it here.</p><a class="btn primary" href="products.html">Shop Now</a></div>';return}const steps=['Order Placed','Processing','Shipped','Out for Delivery','Delivered'];const current=Math.max(0,steps.indexOf(o.status));b.innerHTML=`<div class="tracking-card"><div class="tracking-head"><div><small>ORDER</small><h2>${o.id}</h2></div><span>${o.status}</span></div><div class="timeline">${steps.map((s,i)=>`<div class="track-step ${i<=current?'done':''}"><b>${i<=current?'✓':i+1}</b><span>${s}</span></div>`).join('')}</div><div class="tracking-info"><p><b>Customer:</b> ${o.customer.name}</p><p><b>Delivery:</b> ${o.customer.address}, ${o.customer.city}</p><p><b>Placed:</b> ${new Date(o.date).toLocaleString()}</p></div></div>`}
function renderSeller(){const b=document.getElementById('sellerContainer');if(!b)return;const saved=get('lexMarketSellerProducts',[]);b.innerHTML=`<div class="dashboard-grid"><div class="stat"><span>Products</span><strong>${saved.length+8}</strong></div><div class="stat"><span>Orders</span><strong>${orders().length}</strong></div><div class="stat"><span>Wishlist Saves</span><strong>${wish().length}</strong></div></div><div class="dashboard-card"><div class="heading compact"><h2>Seller Products</h2><button class="btn primary" onclick="addSellerDemo()">+ Add Product</button></div><div class="seller-table">${saved.length?saved.map((p,i)=>`<div><b>${p.name}</b><span>${money(p.price)}</span><button onclick="removeSellerDemo(${i})">Remove</button></div>`).join(''):'<p>No custom products yet. Add a demo product to test the seller flow.</p>'}</div></div>`}
function addSellerDemo(){const s=get('lexMarketSellerProducts',[]);s.push({name:'New LEX Seller Product',price:75000,stock:10});localStorage.setItem('lexMarketSellerProducts',JSON.stringify(s));renderSeller();showToast('Product added')}
function removeSellerDemo(i){const s=get('lexMarketSellerProducts',[]);s.splice(i,1);localStorage.setItem('lexMarketSellerProducts',JSON.stringify(s));renderSeller()}
function renderAdmin(){const b=document.getElementById('adminContainer');if(!b)return;const o=orders(),sales=o.reduce((s,x)=>s+x.total,0);b.innerHTML=`<div class="dashboard-grid"><div class="stat"><span>Total Products</span><strong>${products.length}</strong></div><div class="stat"><span>Total Orders</span><strong>${o.length}</strong></div><div class="stat"><span>Demo Sales</span><strong>${money(sales)}</strong></div></div><div class="dashboard-card"><h2>Recent Orders</h2>${o.length?o.slice().reverse().map(x=>`<div class="admin-order"><b>${x.id}</b><span>${x.customer.name}</span><strong>${money(x.total)}</strong><select onchange="updateOrderStatus('${x.id}',this.value)">${['Order Placed','Processing','Shipped','Out for Delivery','Delivered'].map(s=>`<option ${x.status===s?'selected':''}>${s}</option>`).join('')}</select></div>`).join(''):'<p>No orders yet.</p>'}</div>`}
function updateOrderStatus(id,status){const o=orders(),x=o.find(a=>a.id===id);if(x){x.status=status;localStorage.setItem(ORDER_KEY,JSON.stringify(o));renderAdmin();showToast('Order status updated')}}
function search(){const v=document.getElementById('searchInput')?.value.trim()||'';if(location.pathname.toLowerCase().endsWith('products.html')){currentSearch=v;renderProducts()}else location.href='products.html?search='+encodeURIComponent(v)}
function setup(){updateCounts();document.getElementById('searchButton')?.addEventListener('click',search);document.getElementById('searchInput')?.addEventListener('keydown',e=>{if(e.key==='Enter')search()});document.querySelectorAll('.filter').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));btn.classList.add('active');currentCategory=btn.dataset.category;renderProducts()}));const q=new URLSearchParams(location.search);if(q.get('search')){currentSearch=q.get('search');const i=document.getElementById('searchInput');if(i)i.value=currentSearch}if(q.get('category'))currentCategory=q.get('category');renderHome();renderProducts();renderDeals();renderWishlist();renderCart();renderCheckout();renderProduct();renderAccount();renderTracking();renderSeller();renderAdmin()}
function renderAll(){renderHome();renderProducts();renderWishlist();renderProduct();renderAccount();updateCounts()}
function showToast(msg){let t=document.getElementById('toast');if(!t){t=document.createElement('div');t.id='toast';document.body.appendChild(t)}t.textContent='✓ '+msg;t.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>t.classList.remove('show'),1800)}
document.addEventListener('DOMContentLoaded',setup);
document.addEventListener('submit',e=>{if(e.target.id==='checkoutForm'){e.preventDefault();const data=Object.fromEntries(new FormData(e.target).entries()),c=cart();if(!c.length)return;const sub=c.reduce((s,x)=>s+x.price*x.quantity,0),total=sub+2500;const order={id:'LEX-'+Date.now().toString().slice(-8),customer:data,items:c,total,status:'Order Placed',date:new Date().toISOString()};const list=orders();list.push(order);localStorage.setItem(ORDER_KEY,JSON.stringify(list));localStorage.setItem(USER_KEY,JSON.stringify({name:data.name,email:data.email,phone:data.phone}));localStorage.removeItem(CART_KEY);updateCounts();location.href='confirmation.html?id='+encodeURIComponent(order.id)}});
