/* LEX MARKET PHASE 4 — PRODUCT DISCOVERY & SHOPPING EXPERIENCE */
(()=>{
'use strict';
const C='lexMarketCompare';
const V='lexMarketRecentlyViewed';
const W='lexMarketWishlist';
const CART='lexMarketCart';
const get=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}};
const save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const products=()=>Array.isArray(window.lexProducts)&&window.lexProducts.length?window.lexProducts:(Array.isArray(window.products)?window.products:[]);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>'₦'+Number(n||0).toLocaleString('en-NG');
const idOf=p=>String(p?.id);
const find=id=>products().find(p=>idOf(p)===String(id));
const page=()=>location.pathname.split('/').pop().toLowerCase()||'index.html';
function toast(msg){if(typeof window.showToast==='function')window.showToast(msg);else{let t=document.getElementById('phase4Toast');if(!t){t=document.createElement('div');t.id='phase4Toast';t.className='toast';document.body.appendChild(t)}t.textContent='✓ '+msg;t.classList.add('show');clearTimeout(window.p4t);window.p4t=setTimeout(()=>t.classList.remove('show'),1800)}}
function compare(){return get(C,[])}
function compareCount(){return compare().length}
function updateCompareUI(){document.querySelectorAll('[data-compare-count]').forEach(x=>x.textContent=compareCount());document.querySelectorAll('[data-compare-link]').forEach(x=>x.classList.toggle('has-items',compareCount()>0))}
function toggleCompare(id){let a=compare(),i=a.findIndex(x=>String(x)===String(id));if(i>=0){a.splice(i,1);toast('Removed from comparison')}else{if(a.length>=3){toast('Compare up to 3 products at a time');return}a.push(String(id));toast('Added to comparison')}save(C,a);updateCompareUI();document.querySelectorAll(`[data-p4-compare="${CSS.escape(String(id))}"]`).forEach(b=>{b.textContent=a.some(x=>String(x)===String(id))?'✓ Comparing':'Compare';b.classList.toggle('active',a.some(x=>String(x)===String(id)))})}
function injectCompareButton(){let nav=document.querySelector('header .actions');if(!nav||nav.querySelector('[data-compare-link]'))return;let a=document.createElement('a');a.href='compare.html';a.dataset.compareLink='1';a.innerHTML='⇄<small>Compare <b data-compare-count>0</b></small>';nav.insertBefore(a,nav.firstElementChild);updateCompareUI()}
function enhanceCards(root=document){root.querySelectorAll('.phase3-card,.card').forEach(card=>{if(card.querySelector('.p4-card-tools'))return;let id=card.dataset.productId||card.querySelector('[data-open-product]')?.dataset.openProduct;if(!id)return;let tools=document.createElement('div');tools.className='p4-card-tools';tools.innerHTML=`<button type="button" data-p4-quick="${esc(id)}">Quick View</button><button type="button" data-p4-compare="${esc(id)}">${compare().some(x=>String(x)===String(id))?'✓ Comparing':'Compare'}</button>`;card.querySelector('.card-body')?.appendChild(tools);});
root.querySelectorAll('[data-p4-compare]').forEach(b=>{if(b.dataset.p4Bound)return;b.dataset.p4Bound='1';b.addEventListener('click',e=>{e.stopPropagation();toggleCompare(b.dataset.p4Compare)})});
root.querySelectorAll('[data-p4-quick]').forEach(b=>{if(b.dataset.p4Bound)return;b.dataset.p4Bound='1';b.addEventListener('click',e=>{e.stopPropagation();quickView(b.dataset.p4Quick)})})
root.querySelectorAll('[data-open-product]').forEach(el=>{if(el.dataset.p4OpenBound)return;el.dataset.p4OpenBound='1';el.addEventListener('click',e=>{if(e.target.closest('button'))return;let id=el.dataset.openProduct;location.href='product.html?id='+encodeURIComponent(id)})})}
function quickView(id){let p=find(id);if(!p)return;closeQuick();let d=document.createElement('div');d.className='p4-modal-backdrop';d.id='p4QuickModal';d.innerHTML=`<div class="p4-modal" role="dialog" aria-modal="true"><button class="p4-close" data-p4-close>×</button><div class="p4-quick-grid"><div class="p4-quick-image"><img src="${esc(p.image||'')}" alt="${esc(p.name)}"></div><div class="p4-quick-info"><span class="eyebrow">${esc(p.category||'PRODUCT')}</span><h2>${esc(p.name)}</h2><div class="rating">★ ${Number(p.rating||0).toFixed(1)} <small>(${Number(p.reviews||0)} reviews)</small></div><div class="p4-price"><strong>${money(p.price)}</strong>${Number(p.oldPrice)>Number(p.price)?`<del>${money(p.oldPrice)}</del>`:''}</div><p>${esc(p.description||'Quality product from LEX Market.')}</p><div class="p4-stock">${Number(p.stock)>0?'✓ In stock':'× Out of stock'}</div><div class="p4-modal-actions"><button class="btn primary" data-p4-buy="${esc(id)}" ${Number(p.stock)<=0?'disabled':''}>🛒 Add to Cart</button><a class="btn secondary" href="product.html?id=${encodeURIComponent(id)}">View Details</a></div></div></div></div>`;document.body.appendChild(d);d.addEventListener('click',e=>{if(e.target===d||e.target.closest('[data-p4-close]'))closeQuick();let b=e.target.closest('[data-p4-buy]');if(b){addCart(id);closeQuick()}})}
function closeQuick(){document.getElementById('p4QuickModal')?.remove()}
function addCart(id){let p=find(id);if(!p)return;let c=get(CART,[]),i=c.findIndex(x=>String(x.id)===String(id));if(i>=0)c[i].quantity=Number(c[i].quantity||0)+1;else c.push({id:p.id,name:p.name,price:p.price,image:p.image,quantity:1});save(CART,c);document.dispatchEvent(new Event('storage'));if(typeof window.updateCounts==='function')window.updateCounts();toast(`${p.name} added to cart`)}
function productEnhance(){if(page()!=='product.html')return;let id=new URLSearchParams(location.search).get('id'),p=find(id),host=document.getElementById('productDetails');if(!p||!host)return;let info=host.querySelector('.details-info');if(info&&!info.querySelector('.p4-buy-now')){let actions=info.querySelector('.product-actions');if(actions){let b=document.createElement('button');b.className='btn primary p4-buy-now';b.type='button';b.textContent='⚡ Buy Now';b.addEventListener('click',()=>{addCart(id);location.href='checkout.html'});actions.appendChild(b)}}
let details=host.querySelector('.details');if(details&&!host.querySelector('.p4-trust-row')){let trust=document.createElement('div');trust.className='p4-trust-row';trust.innerHTML='<div>🚚<b>Reliable Delivery</b><small>Delivery fee shown at checkout</small></div><div>🔒<b>Secure Checkout</b><small>Your payment is protected</small></div><div>↩️<b>Easy Support</b><small>Contact LEX for help</small></div>';details.insertAdjacentElement('afterend',trust)}
if(!host.querySelector('.p4-info-tabs')){let tabs=document.createElement('div');tabs.className='p4-info-tabs';tabs.innerHTML=`<div class="p4-tabs"><button class="active" data-tab="description">Description</button><button data-tab="delivery">Delivery & Returns</button><button data-tab="seller">Seller</button></div><div class="p4-tab-panel active" data-panel="description"><h3>About this product</h3><p>${esc(p.description||'This product is available from LEX Market. Product information is provided by the seller.')}</p><ul><li>Category: ${esc(p.category||'Other')}</li><li>Availability: ${Number(p.stock||0)>0?'In stock':'Currently unavailable'}</li><li>Rating: ${Number(p.rating||0).toFixed(1)} / 5</li></ul></div><div class="p4-tab-panel" data-panel="delivery"><h3>Delivery & Returns</h3><p>Delivery options and applicable fees are shown during checkout. For order issues, contact LEX Market support with your order number.</p><p>Keep your order confirmation and product condition details if you need support.</p></div><div class="p4-tab-panel" data-panel="seller"><h3>Seller information</h3><p><b>${esc(p.sellerName||'LEX Market Seller')}</b></p><p>Seller information shown here comes from the marketplace catalog.</p></div>`;host.appendChild(tabs);tabs.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>{tabs.querySelectorAll('[data-tab]').forEach(x=>x.classList.remove('active'));tabs.querySelectorAll('[data-panel]').forEach(x=>x.classList.remove('active'));b.classList.add('active');tabs.querySelector(`[data-panel="${b.dataset.tab}"]`)?.classList.add('active')}))}
recommendations(host,p)
/* Phase 10 provides the single mobile sticky Add to Cart bar. */}
function recommendations(host,p){let related=products().filter(x=>String(x.id)!==String(p.id)&&String(x.category||'').toLowerCase()===String(p.category||'').toLowerCase()).slice(0,4);if(related.length<4)related=related.concat(products().filter(x=>String(x.id)!==String(p.id)&&!related.some(r=>String(r.id)===String(x.id))).slice(0,4-related.length));if(!related.length||host.querySelector('.p4-recommend'))return;let s=document.createElement('section');s.className='p4-recommend';s.innerHTML=`<div class="heading"><div><span class="eyebrow">YOU MAY ALSO LIKE</span><h2>More like this</h2></div><a href="products.html">Browse All →</a></div><div class="product-grid">${related.map(p4Card).join('')}</div>`;host.appendChild(s);enhanceCards(s)}
function p4Card(p){let d=Number(p.discount||0);return `<article class="card phase3-card" data-product-id="${esc(p.id)}"><div class="pic" data-open-product="${esc(p.id)}">${d?`<span class="discount">${d}% OFF</span>`:''}<div class="product-photo"><img class="product-image" src="${esc(p.image||'')}" alt="${esc(p.name)}" loading="lazy"></div></div><div class="card-body"><small>${esc(p.category||'Other')}</small><h3 data-open-product="${esc(p.id)}">${esc(p.name)}</h3><div class="rating">★ ${Number(p.rating||0).toFixed(1)} <small>(${Number(p.reviews||0)})</small></div><div class="price"><strong>${money(p.price)}</strong>${Number(p.oldPrice)>Number(p.price)?`<del>${money(p.oldPrice)}</del>`:''}</div></div></article>`}
function comparePage(){if(page()!=='compare.html')return;let host=document.getElementById('compareContainer');if(!host)return;let ps=compare().map(find).filter(Boolean);if(!ps.length){host.innerHTML='<div class="empty"><div>⇄</div><h2>No Products to Compare</h2><p>Add products from the marketplace to compare them side by side.</p><a class="btn primary" href="products.html">Browse Products</a></div>';return}host.innerHTML=`<div class="p4-compare-head"><div><span class="eyebrow">SIDE-BY-SIDE</span><h1>Compare Products</h1><p>Compare up to three products before you decide.</p></div><button class="btn secondary" id="clearCompare">Clear All</button></div><div class="p4-compare-table"><div class="p4-compare-row p4-compare-products"><div class="p4-label">PRODUCT</div>${ps.map(p=>`<div class="p4-compare-cell"><button class="p4-remove" data-remove-compare="${esc(p.id)}">×</button><div class="p4-compare-img"><img src="${esc(p.image||'')}" alt="${esc(p.name)}"></div><h3>${esc(p.name)}</h3><div class="rating">★ ${Number(p.rating||0).toFixed(1)} <small>(${Number(p.reviews||0)})</small></div></div>`).join('')}</div>${[['Price',p=>money(p.price)],['Old Price',p=>Number(p.oldPrice)>Number(p.price)?money(p.oldPrice):'—'],['Discount',p=>Number(p.discount||0)?`${p.discount}% OFF`:'—'],['Category',p=>p.category||'Other'],['Availability',p=>Number(p.stock||0)>0?`${p.stock} in stock`:'Out of stock'],['Seller',p=>p.sellerName||'LEX Market Seller']].map(([label,fn])=>`<div class="p4-compare-row"><div class="p4-label">${label}</div>${ps.map(p=>`<div class="p4-compare-cell"><b>${esc(fn(p))}</b></div>`).join('')}</div>`).join('')}<div class="p4-compare-row"><div class="p4-label">ACTION</div>${ps.map(p=>`<div class="p4-compare-cell"><a class="btn secondary" href="product.html?id=${encodeURIComponent(p.id)}">View Product</a></div>`).join('')}</div></div>`;host.querySelector('#clearCompare')?.addEventListener('click',()=>{save(C,[]);comparePage();updateCompareUI()});host.querySelectorAll('[data-remove-compare]').forEach(b=>b.addEventListener('click',()=>{save(C,compare().filter(x=>String(x)!==String(b.dataset.removeCompare)));comparePage();updateCompareUI()}))}
function cartRecommendations(){if(page()!=='cart.html')return;let host=document.getElementById('cartContainer');if(!host||host.querySelector('.p4-cart-recommend'))return;let ids=get(CART,[]).map(x=>String(x.id));let ps=products().filter(p=>!ids.includes(String(p.id))).slice(0,4);if(!ps.length)return;let s=document.createElement('section');s.className='p4-cart-recommend';s.innerHTML=`<div class="heading"><div><span class="eyebrow">KEEP SHOPPING</span><h2>Popular picks</h2></div><a href="products.html">See All →</a></div><div class="product-grid">${ps.map(p4Card).join('')}</div>`;host.appendChild(s);enhanceCards(s)}
function run(){injectCompareButton();updateCompareUI();enhanceCards();productEnhance();comparePage();cartRecommendations();document.querySelectorAll('.p4-card-tools').forEach(x=>x.closest('.card')?.classList.add('p4-enhanced'))}
window.addEventListener('lex-catalog-updated',run);window.addEventListener('storage',run);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',run,{once:true});else run();
})();
