/* LEX MARKET PHASE 5 — PERSONALIZATION, NOTIFICATIONS & APP EXPERIENCE */
(()=>{
'use strict';
const SIGNAL='lexMarketSignals', CART='lexMarketCart', WISH='lexMarketWishlist', VIEWED='lexMarketRecentlyViewed', PRICE='lexMarketPriceSnapshots', DISMISS='lexMarketP5Dismiss';
const get=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}};
const save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const catalog=()=>Array.isArray(window.lexProducts)?window.lexProducts:[];
const page=()=>location.pathname.split('/').pop().toLowerCase()||'index.html';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>'₦'+Number(n||0).toLocaleString('en-NG');
const norm=v=>String(v??'').toLowerCase().trim();
const toast=msg=>{if(typeof window.showToast==='function')return window.showToast(msg);let t=document.getElementById('p5Toast');if(!t){t=document.createElement('div');t.id='p5Toast';t.className='toast';document.body.appendChild(t)}t.textContent='✓ '+msg;t.classList.add('show');clearTimeout(window.p5toast);window.p5toast=setTimeout(()=>t.classList.remove('show'),1900)};
function signals(){return get(SIGNAL,{views:{},categories:{},cart:0,wishlist:0,searches:0})}
function bump(type,p){let s=signals();if(type==='view'&&p){s.views[p.id]=(s.views[p.id]||0)+1;let c=String(p.category||'Other');s.categories[c]=(s.categories[c]||0)+1}else if(type==='cart')s.cart++;else if(type==='wishlist')s.wishlist++;else if(type==='search')s.searches++;save(SIGNAL,s)}
function trackInteractions(){document.addEventListener('click',e=>{let open=e.target.closest('[data-open-product]');if(open){let p=catalog().find(x=>String(x.id)===String(open.dataset.openProduct));if(p)bump('view',p)}let add=e.target.closest('[data-add-cart], [data-p4-buy]');if(add)bump('cart');let wish=e.target.closest('[data-wish]');if(wish)bump('wishlist')},{passive:true});let old=localStorage.getItem('lexMarketLastSearchCount');if(old===null)save('lexMarketLastSearchCount',0)}
function preferenceCategories(){let s=signals(),cats=Object.entries(s.categories||{}).sort((a,b)=>b[1]-a[1]).map(x=>x[0]);let viewed=get(VIEWED,[]).map(id=>catalog().find(p=>String(p.id)===String(id))).filter(Boolean).map(p=>p.category);cats=[...cats,...viewed];return [...new Set(cats)].slice(0,4)}
function score(p){let s=signals(),cats=preferenceCategories(),z=Number(p.rating||0)*2+Number(p.discount||0)/10;if(cats.includes(p.category))z+=35-(cats.indexOf(p.category)*5);let views=Number(s.views?.[p.id]||0);z+=views*8;if(Number(p.stock||0)>0)z+=3;return z}
function card(p){let old=Number(p.oldPrice||0),price=Number(p.price||0),d=Number(p.discount||0),stock=Number(p.stock||0);return `<article class="card phase5-card" data-product-id="${esc(p.id)}"><div class="pic" data-open-product="${esc(p.id)}">${d?`<span class="discount">${d}% OFF</span>`:''}<div class="product-photo"><img class="product-image" src="${esc(p.image||'')}" alt="${esc(p.name)}" loading="lazy"></div></div><div class="card-body"><small>${esc(p.category||'Other')}${p.sellerName?` · ${esc(p.sellerName)}`:''}</small><h3 data-open-product="${esc(p.id)}">${esc(p.name)}</h3><div class="rating">★ ${Number(p.rating||0).toFixed(1)} <small>(${Number(p.reviews||0)})</small></div><div class="price"><strong>${money(price)}</strong>${old>price?`<del>${money(old)}</del>`:''}</div><button class="add" data-p5-add="${esc(p.id)}" ${stock===0?'disabled':''}>${stock===0?'Out of Stock':'Add to Cart'}</button></div></article>`}
function addCart(id){let p=catalog().find(x=>String(x.id)===String(id));if(!p)return;let c=get(CART,[]),i=c.findIndex(x=>String(x.id)===String(id));if(i>=0)c[i].quantity=Number(c[i].quantity||0)+1;else c.push({id:p.id,name:p.name,price:p.price,image:p.image,quantity:1});save(CART,c);bump('cart');document.dispatchEvent(new Event('storage'));toast(`${p.name} added to cart`);updateHeader()}
function updateHeader(){let cart=get(CART,[]).reduce((n,x)=>n+Number(x.quantity||0),0),wish=get(WISH,[]).length;document.querySelectorAll('.cart-link').forEach(a=>{let b=a.querySelector('.cart-badge');if(!b){b=document.createElement('span');b.className='cart-badge';a.appendChild(b)}b.textContent=cart;b.classList.toggle('empty',cart===0)});document.querySelectorAll('a[href="wishlist.html"]').forEach(a=>{let b=a.querySelector('.p5-badge');if(!b){b=document.createElement('span');b.className='p5-badge';a.appendChild(b)}b.textContent=wish;b.classList.toggle('empty',wish===0)})}
function injectNotifications(){let actions=document.querySelector('header .actions');if(!actions||actions.querySelector('[data-p5-notify]'))return;let b=document.createElement('button');b.type='button';b.className='p5-notify-btn';b.dataset.p5Notify='1';b.innerHTML='🔔<small>Alerts</small><span class="p5-alert-dot"></span>';actions.insertBefore(b,actions.firstElementChild);b.addEventListener('click',openAlerts)}
function alerts(){let out=[],wish=get(WISH,[]),snap=get(PRICE,{});wish.forEach(w=>{let p=catalog().find(x=>String(x.id)===String(w.id));if(!p)return;let old=Number(snap[p.id]??p.price),now=Number(p.price);if(now<old)out.push({type:'price',title:'Price dropped',text:`${p.name} is now ${money(now)}.`,productId:p.id});if(Number(p.stock||0)>0&&Number(p.stock)<=3)out.push({type:'stock',title:'Low stock',text:`Only ${p.stock} left: ${p.name}.`,productId:p.id})});if(!out.length)out.push({type:'info',title:'You’re all caught up',text:'We’ll show useful alerts for items you save.'});return out.slice(0,6)}
function openAlertDetail(item){document.getElementById('p5AlertDetail')?.remove();const d=document.createElement('div');d.id='p5AlertDetail';d.className='p7-modal-backdrop';d.innerHTML=`<div class="p7-modal"><button class="p7-close" type="button" data-close>×</button><span class="eyebrow">LEX MARKET</span><h2 style="margin:6px 0 8px">${esc(item.title)}</h2><p style="line-height:1.6;color:#666">${esc(item.text)}</p><small style="display:block;color:#888;margin-top:12px">${item.type==='price'?'Price alert':item.type==='stock'?'Stock alert':'LEX Market alert'}</small>${item.productId?`<a class="btn primary" style="display:inline-block;margin-top:18px" href="product.html?id=${encodeURIComponent(item.productId)}">View Product</a>`:''}</div>`;document.body.appendChild(d);d.querySelector('[data-close]').onclick=()=>d.remove();d.addEventListener('click',e=>{if(e.target===d)d.remove()})}
function openAlerts(){let old=document.getElementById('p5Alerts');if(old){old.remove();return}let a=alerts(),d=document.createElement('div');d.id='p5Alerts';d.className='p5-alert-backdrop';d.innerHTML=`<div class="p5-alert-panel"><div class="p5-alert-head"><div><span class="eyebrow">LEX MARKET</span><h3>Your Alerts</h3></div><button type="button" data-p5-close>×</button></div><div class="p5-alert-list">${a.map((x,i)=>`<button type="button" class="p5-alert-item" data-alert-index="${i}" style="text-align:left;width:100%;cursor:${x.productId?'pointer':'default'}"><b>${x.type==='price'?'↘':'•'} ${esc(x.title)}</b><p>${esc(x.text)}</p>${x.productId?'<small style="color:#5b2be0;font-weight:700">Tap for details →</small>':''}</button>`).join('')}</div><a class="btn primary" href="wishlist.html">View Wishlist</a></div>`;document.body.appendChild(d);d.querySelector('[data-p5-close]').onclick=()=>d.remove();d.addEventListener('click',e=>{if(e.target===d)d.remove()});d.querySelectorAll('[data-alert-index]').forEach(el=>el.onclick=()=>{const item=a[Number(el.dataset.alertIndex)];if(item?.productId)openAlertDetail(item)})}
window.lexOpenAlerts=openAlerts;
function snapshotPrices(){let snap=get(PRICE,{}),changed=false;catalog().forEach(p=>{let n=Number(p.price||0);if(snap[p.id]===undefined){snap[p.id]=n;changed=true}});if(changed)save(PRICE,snap)}
function personalizedHome(){if(page()!=='index.html')return;let host=document.getElementById('featuredProducts')?.parentElement?.parentElement;if(!host||document.getElementById('p5ForYou'))return;let pref=preferenceCategories(),all=catalog().slice().sort((a,b)=>score(b)-score(a));let picks=all.filter(p=>pref.includes(p.category)).concat(all.filter(p=>!pref.includes(p.category)));picks=[...new Map(picks.map(p=>[String(p.id),p])).values()].slice(0,4);if(!picks.length)return;let section=document.createElement('section');section.id='p5ForYou';section.className='section p5-section';section.innerHTML=`<div class="wrap"><div class="p5-personal-head"><div><span class="eyebrow">MADE FOR YOU</span><h2>Picked for you</h2><p>${pref.length?`Based on your interest in ${pref.slice(0,2).join(' & ')}.`:'Popular products to help you get started.'}</p></div><a href="products.html">Explore All →</a></div><div class="grid product-grid">${picks.map(card).join('')}</div></div>`;host.closest('.section')?.insertAdjacentElement('afterend',section);bindCards(section)}
function bindCards(root){root.querySelectorAll('[data-p5-add]').forEach(b=>{b.onclick=e=>{e.stopPropagation();addCart(b.dataset.p5Add)}});root.querySelectorAll('[data-open-product]').forEach(el=>{el.addEventListener('click',()=>{let id=el.dataset.openProduct,v=get(VIEWED,[]).filter(x=>String(x)!==String(id));v.unshift(id);save(VIEWED,v.slice(0,8))})})}
function accountPanel(){if(page()!=='account.html')return;let host=document.getElementById('accountContainer');if(!host||document.getElementById('p5AccountPanel'))return;let pref=preferenceCategories(),views=get(VIEWED,[]).length,wish=get(WISH,[]).length;let s=document.createElement('section');s.id='p5AccountPanel';s.className='p5-account-panel';s.innerHTML=`<div class="p5-account-title"><div><span class="eyebrow">YOUR LEX</span><h3>Shopping activity</h3></div><span class="p5-status">Personalized</span></div><div class="p5-stats"><div><strong>${views}</strong><small>Recent views</small></div><div><strong>${wish}</strong><small>Saved items</small></div><div><strong>${pref.length}</strong><small>Interests</small></div></div><div class="p5-interest"><b>Your interests</b><div>${(pref.length?pref:['Explore the marketplace']).map(c=>`<a href="products.html?category=${encodeURIComponent(c)}">${esc(c)} →</a>`).join('')}</div></div>`;host.appendChild(s)}
function installPrompt(){let deferred=null;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferred=e;let existing=get(DISMISS,false);if(existing)return;showInstall(deferred)});function showInstall(p){if(document.getElementById('p5Install'))return;let d=document.createElement('div');d.id='p5Install';d.className='p5-install';d.innerHTML='<div><b>Get LEX Market on your home screen</b><small>Open LEX faster like an app.</small></div><button type="button" data-p5-install>Install</button><button type="button" data-p5-dismiss>×</button>';document.body.appendChild(d);d.querySelector('[data-p5-install]').onclick=async()=>{if(p){p.prompt();try{await p.userChoice}catch{}p=null}d.remove()};d.querySelector('[data-p5-dismiss]').onclick=()=>{save(DISMISS,true);d.remove()}}
if('serviceWorker' in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(()=>{}))}}
function run(){injectNotifications();updateHeader();snapshotPrices();personalizedHome();accountPanel();trackOnce()}
let tracked=false;function trackOnce(){if(tracked)return;tracked=true;trackInteractions()}
window.addEventListener('lex-catalog-updated',()=>{snapshotPrices();run()});window.addEventListener('storage',()=>{updateHeader();snapshotPrices()});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',run,{once:true});else run();installPrompt();
})();
